export const labels = {
  supplier: "Supplier",
  supplierName: "East coast fruits & vegetables",
  shippingDate: "Shipping date",
  total: "Total",
  category: "Category",
  department: "Department",
  status: "Status",
  search: "Search...",
  missingProduct: "Missing product",
  no: "No",
  yes: "Yes",
  approved: "Approved",
  missing: "Missing",
  price: "Price",
  quantity: "Quantity",
  chooseReason: "Choose reason",
  quantityIsNotTheSame: "Quantity is not the same",
  priceIsNotTheSame: "Price is not the same",
  cancel: "Cancel",
  send: "Send",
}